tictactoe: Remove undeclared "col" usage in draw_winning_line()
I forgot to remove col while implementing commit 1c53c6f3b75 ("tictactoe:
Combine all winning line algorithms into one function"). Since the position
for posX and posY would be the same if I were to replace "col" with "row",
just remove the variable usage all together and directly calculate inside
pg.draw.line().
While at it, edit "row" parameter of draw_winning_line() to "pos" to match
our intention.

This fixes the following error when we try to win vertically:

Traceback (most recent call last):
  File "/home/tashar/tic-tac-toe/tictactoe.py", line 180, in <module>
    event_handler()
  File "/home/tashar/tic-tac-toe/tictactoe.py", line 160, in event_handler
    user_click()
  File "/home/tashar/tic-tac-toe/tictactoe.py", line 131, in user_click
    if check_winner() or check_draw():
       ^^^^^^^^^^^^^^
  File "/home/tashar/tic-tac-toe/tictactoe.py", line 84, in check_winner
    draw_winning_line(game_data['board'][0][i], 'vertical', i)
  File "/home/tashar/tic-tac-toe/tictactoe.py", line 65, in draw_winning_line
    posX = col * CELL_SIZE + CELL_SIZE // 2
           ^^^
NameError: name 'col' is not defined

Fixes: 1c53c6f3b75 ("tictactoe: Combine all winning line algorithms into one function")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>